// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmostriliza/game.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GameState int32

const (
	GameState_OPEN    GameState = 0
	GameState_ONGOING GameState = 1
	GameState_OWINS   GameState = 2
	GameState_XWINS   GameState = 3
	GameState_DRAW    GameState = 4
)

var GameState_name = map[int32]string{
	0: "OPEN",
	1: "ONGOING",
	2: "OWINS",
	3: "XWINS",
	4: "DRAW",
}

var GameState_value = map[string]int32{
	"OPEN":    0,
	"ONGOING": 1,
	"OWINS":   2,
	"XWINS":   3,
	"DRAW":    4,
}

func (x GameState) String() string {
	return proto.EnumName(GameState_name, int32(x))
}

func (GameState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b89d22db3ab81f20, []int{0}
}

type Mark int32

const (
	Mark_EMPTY   Mark = 0
	Mark_XPLAYER Mark = 1
	Mark_OPLAYER Mark = 2
)

var Mark_name = map[int32]string{
	0: "EMPTY",
	1: "XPLAYER",
	2: "OPLAYER",
}

var Mark_value = map[string]int32{
	"EMPTY":   0,
	"XPLAYER": 1,
	"OPLAYER": 2,
}

func (x Mark) String() string {
	return proto.EnumName(Mark_name, int32(x))
}

func (Mark) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b89d22db3ab81f20, []int{1}
}

type Game struct {
	Creator     string    `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id          string    `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Rows        uint32    `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols        uint32    `protobuf:"varint,4,opt,name=cols,proto3" json:"cols,omitempty"`
	Strike      uint32    `protobuf:"varint,5,opt,name=strike,proto3" json:"strike,omitempty"`
	Reward      uint32    `protobuf:"varint,6,opt,name=reward,proto3" json:"reward,omitempty"`
	GameState   GameState `protobuf:"varint,7,opt,name=gameState,proto3,enum=misaakidis.cosmostriliza.cosmostriliza.GameState" json:"gameState,omitempty"`
	Board       []Mark    `protobuf:"varint,8,rep,packed,name=board,proto3,enum=misaakidis.cosmostriliza.cosmostriliza.Mark" json:"board,omitempty"`
	NumOfMoves  uint32    `protobuf:"varint,9,opt,name=numOfMoves,proto3" json:"numOfMoves,omitempty"`
	Guest       string    `protobuf:"bytes,10,opt,name=guest,proto3" json:"guest,omitempty"`
	CreatorMark Mark      `protobuf:"varint,11,opt,name=creatorMark,proto3,enum=misaakidis.cosmostriliza.cosmostriliza.Mark" json:"creatorMark,omitempty"`
	GuestMark   Mark      `protobuf:"varint,12,opt,name=guestMark,proto3,enum=misaakidis.cosmostriliza.cosmostriliza.Mark" json:"guestMark,omitempty"`
	NextMark    Mark      `protobuf:"varint,13,opt,name=nextMark,proto3,enum=misaakidis.cosmostriliza.cosmostriliza.Mark" json:"nextMark,omitempty"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}
func (*Game) Descriptor() ([]byte, []int) {
	return fileDescriptor_b89d22db3ab81f20, []int{0}
}
func (m *Game) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Game) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Game.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Game) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game.Merge(m, src)
}
func (m *Game) XXX_Size() int {
	return m.Size()
}
func (m *Game) XXX_DiscardUnknown() {
	xxx_messageInfo_Game.DiscardUnknown(m)
}

var xxx_messageInfo_Game proto.InternalMessageInfo

func (m *Game) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Game) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Game) GetRows() uint32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func (m *Game) GetCols() uint32 {
	if m != nil {
		return m.Cols
	}
	return 0
}

func (m *Game) GetStrike() uint32 {
	if m != nil {
		return m.Strike
	}
	return 0
}

func (m *Game) GetReward() uint32 {
	if m != nil {
		return m.Reward
	}
	return 0
}

func (m *Game) GetGameState() GameState {
	if m != nil {
		return m.GameState
	}
	return GameState_OPEN
}

func (m *Game) GetBoard() []Mark {
	if m != nil {
		return m.Board
	}
	return nil
}

func (m *Game) GetNumOfMoves() uint32 {
	if m != nil {
		return m.NumOfMoves
	}
	return 0
}

func (m *Game) GetGuest() string {
	if m != nil {
		return m.Guest
	}
	return ""
}

func (m *Game) GetCreatorMark() Mark {
	if m != nil {
		return m.CreatorMark
	}
	return Mark_EMPTY
}

func (m *Game) GetGuestMark() Mark {
	if m != nil {
		return m.GuestMark
	}
	return Mark_EMPTY
}

func (m *Game) GetNextMark() Mark {
	if m != nil {
		return m.NextMark
	}
	return Mark_EMPTY
}

type MsgCreateGame struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Rows    uint32 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols    uint32 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	Strike  uint32 `protobuf:"varint,4,opt,name=strike,proto3" json:"strike,omitempty"`
	Reward  uint32 `protobuf:"varint,5,opt,name=reward,proto3" json:"reward,omitempty"`
}

func (m *MsgCreateGame) Reset()         { *m = MsgCreateGame{} }
func (m *MsgCreateGame) String() string { return proto.CompactTextString(m) }
func (*MsgCreateGame) ProtoMessage()    {}
func (*MsgCreateGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_b89d22db3ab81f20, []int{1}
}
func (m *MsgCreateGame) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateGame.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateGame.Merge(m, src)
}
func (m *MsgCreateGame) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateGame) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateGame.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateGame proto.InternalMessageInfo

func (m *MsgCreateGame) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateGame) GetRows() uint32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func (m *MsgCreateGame) GetCols() uint32 {
	if m != nil {
		return m.Cols
	}
	return 0
}

func (m *MsgCreateGame) GetStrike() uint32 {
	if m != nil {
		return m.Strike
	}
	return 0
}

func (m *MsgCreateGame) GetReward() uint32 {
	if m != nil {
		return m.Reward
	}
	return 0
}

type MsgJoinGame struct {
	Guest string `protobuf:"bytes,1,opt,name=guest,proto3" json:"guest,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgJoinGame) Reset()         { *m = MsgJoinGame{} }
func (m *MsgJoinGame) String() string { return proto.CompactTextString(m) }
func (*MsgJoinGame) ProtoMessage()    {}
func (*MsgJoinGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_b89d22db3ab81f20, []int{2}
}
func (m *MsgJoinGame) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgJoinGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgJoinGame.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgJoinGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgJoinGame.Merge(m, src)
}
func (m *MsgJoinGame) XXX_Size() int {
	return m.Size()
}
func (m *MsgJoinGame) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgJoinGame.DiscardUnknown(m)
}

var xxx_messageInfo_MsgJoinGame proto.InternalMessageInfo

func (m *MsgJoinGame) GetGuest() string {
	if m != nil {
		return m.Guest
	}
	return ""
}

func (m *MsgJoinGame) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MsgCommitMove struct {
	Player Mark  `protobuf:"varint,1,opt,name=player,proto3,enum=misaakidis.cosmostriliza.cosmostriliza.Mark" json:"player,omitempty"`
	Row    int32 `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	Col    int32 `protobuf:"varint,3,opt,name=col,proto3" json:"col,omitempty"`
}

func (m *MsgCommitMove) Reset()         { *m = MsgCommitMove{} }
func (m *MsgCommitMove) String() string { return proto.CompactTextString(m) }
func (*MsgCommitMove) ProtoMessage()    {}
func (*MsgCommitMove) Descriptor() ([]byte, []int) {
	return fileDescriptor_b89d22db3ab81f20, []int{3}
}
func (m *MsgCommitMove) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCommitMove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCommitMove.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCommitMove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCommitMove.Merge(m, src)
}
func (m *MsgCommitMove) XXX_Size() int {
	return m.Size()
}
func (m *MsgCommitMove) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCommitMove.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCommitMove proto.InternalMessageInfo

func (m *MsgCommitMove) GetPlayer() Mark {
	if m != nil {
		return m.Player
	}
	return Mark_EMPTY
}

func (m *MsgCommitMove) GetRow() int32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *MsgCommitMove) GetCol() int32 {
	if m != nil {
		return m.Col
	}
	return 0
}

func init() {
	proto.RegisterEnum("misaakidis.cosmostriliza.cosmostriliza.GameState", GameState_name, GameState_value)
	proto.RegisterEnum("misaakidis.cosmostriliza.cosmostriliza.Mark", Mark_name, Mark_value)
	proto.RegisterType((*Game)(nil), "misaakidis.cosmostriliza.cosmostriliza.Game")
	proto.RegisterType((*MsgCreateGame)(nil), "misaakidis.cosmostriliza.cosmostriliza.MsgCreateGame")
	proto.RegisterType((*MsgJoinGame)(nil), "misaakidis.cosmostriliza.cosmostriliza.MsgJoinGame")
	proto.RegisterType((*MsgCommitMove)(nil), "misaakidis.cosmostriliza.cosmostriliza.MsgCommitMove")
}

func init() { proto.RegisterFile("cosmostriliza/game.proto", fileDescriptor_b89d22db3ab81f20) }

var fileDescriptor_b89d22db3ab81f20 = []byte{
	// 538 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6e, 0xda, 0x4c,
	0x14, 0x65, 0x8c, 0x0d, 0xf8, 0xf2, 0x81, 0xac, 0x51, 0xf4, 0x69, 0xd4, 0x85, 0x85, 0x58, 0x54,
	0x28, 0x6d, 0x41, 0x4d, 0x76, 0xdd, 0x85, 0x06, 0xd1, 0x44, 0x05, 0x23, 0x27, 0x52, 0x92, 0xee,
	0x8c, 0x99, 0xba, 0x23, 0x30, 0x83, 0x3c, 0xa6, 0x84, 0xee, 0xfa, 0x06, 0x7d, 0x9d, 0xbe, 0x41,
	0x97, 0x59, 0x76, 0x59, 0xc1, 0x8b, 0x54, 0x33, 0xc3, 0x6f, 0x95, 0xaa, 0x49, 0x76, 0xe7, 0x1e,
	0xcd, 0x39, 0x73, 0xef, 0xdc, 0xa3, 0x01, 0x12, 0x72, 0x11, 0x73, 0x91, 0x26, 0x6c, 0xc4, 0xbe,
	0x04, 0x8d, 0x28, 0x88, 0x69, 0x7d, 0x92, 0xf0, 0x94, 0xe3, 0xe7, 0x31, 0x13, 0x41, 0x30, 0x64,
	0x03, 0x26, 0xea, 0x7b, 0x87, 0xf6, 0xab, 0x67, 0x07, 0x11, 0x8f, 0xb8, 0x92, 0x34, 0x24, 0xd2,
	0xea, 0xea, 0x77, 0x13, 0xcc, 0x76, 0x10, 0x53, 0x4c, 0x20, 0x1f, 0x26, 0x34, 0x48, 0x79, 0x42,
	0x50, 0x05, 0xd5, 0x6c, 0x7f, 0x5d, 0xe2, 0x32, 0x18, 0x6c, 0x40, 0x0c, 0x45, 0x1a, 0x6c, 0x80,
	0x31, 0x98, 0x09, 0x9f, 0x09, 0x92, 0xad, 0xa0, 0x5a, 0xc9, 0x57, 0x58, 0x72, 0x21, 0x1f, 0x09,
	0x62, 0x6a, 0x4e, 0x62, 0xfc, 0x3f, 0xe4, 0xe4, 0xe5, 0x43, 0x4a, 0x2c, 0xc5, 0xae, 0x2a, 0xc9,
	0x27, 0x74, 0x16, 0x24, 0x03, 0x92, 0xd3, 0xbc, 0xae, 0xb0, 0x07, 0xb6, 0x1c, 0xeb, 0x22, 0x0d,
	0x52, 0x4a, 0xf2, 0x15, 0x54, 0x2b, 0x1f, 0xbd, 0xae, 0x3f, 0x6c, 0xb8, 0x7a, 0x7b, 0x2d, 0xf4,
	0xb7, 0x1e, 0xb8, 0x09, 0x56, 0x9f, 0xcb, 0x7b, 0x0a, 0x95, 0x6c, 0xad, 0x7c, 0xf4, 0xf2, 0xa1,
	0x66, 0x9d, 0x20, 0x19, 0xfa, 0x5a, 0x8a, 0x5d, 0x80, 0xf1, 0x34, 0xf6, 0x3e, 0x76, 0xf8, 0x67,
	0x2a, 0x88, 0xad, 0x1a, 0xde, 0x61, 0xf0, 0x01, 0x58, 0xd1, 0x94, 0x8a, 0x94, 0x80, 0x7a, 0x1f,
	0x5d, 0xe0, 0x2e, 0x14, 0x57, 0xaf, 0x27, 0xbd, 0x48, 0x51, 0x0d, 0xf3, 0xb8, 0xfb, 0x77, 0x0d,
	0xf0, 0x39, 0xd8, 0xca, 0x58, 0xb9, 0xfd, 0xf7, 0x04, 0xb7, 0xad, 0x1c, 0xbf, 0x83, 0xc2, 0x98,
	0xde, 0x6a, 0xab, 0xd2, 0x13, 0xac, 0x36, 0xea, 0xea, 0x57, 0x04, 0xa5, 0x8e, 0x88, 0xde, 0xca,
	0x46, 0xe9, 0x3f, 0x42, 0xb4, 0x0e, 0x8d, 0x71, 0x4f, 0x68, 0xb2, 0xf7, 0x86, 0xc6, 0xfc, 0x4b,
	0x68, 0xac, 0xdd, 0xd0, 0x54, 0x8f, 0xa1, 0xd8, 0x11, 0xd1, 0x39, 0x67, 0x63, 0xd5, 0xc0, 0x66,
	0x1d, 0x68, 0x77, 0x1d, 0x7f, 0x24, 0xb8, 0x3a, 0xd7, 0x7d, 0xf3, 0x38, 0x66, 0xa9, 0x5c, 0x23,
	0x3e, 0x85, 0xdc, 0x64, 0x14, 0xcc, 0xa9, 0x6e, 0xfb, 0xb1, 0x2f, 0xb2, 0xd2, 0x62, 0x07, 0xb2,
	0x09, 0x9f, 0xa9, 0x7b, 0x2c, 0x5f, 0x42, 0xc9, 0x84, 0x7c, 0xa4, 0x06, 0xb4, 0x7c, 0x09, 0x0f,
	0x9b, 0x60, 0x6f, 0xb2, 0x8a, 0x0b, 0x60, 0x7a, 0xbd, 0x56, 0xd7, 0xc9, 0xe0, 0x22, 0xe4, 0xbd,
	0x6e, 0xdb, 0x3b, 0xeb, 0xb6, 0x1d, 0x84, 0x6d, 0xb0, 0xbc, 0xab, 0xb3, 0xee, 0x85, 0x63, 0x48,
	0x78, 0xad, 0x60, 0x56, 0x1e, 0x3e, 0xf5, 0x4f, 0xae, 0x1c, 0xf3, 0xf0, 0x05, 0x98, 0x6a, 0x93,
	0x36, 0x58, 0xad, 0x4e, 0xef, 0xf2, 0x46, 0xeb, 0xaf, 0x7b, 0xef, 0x4f, 0x6e, 0x5a, 0xbe, 0x83,
	0x94, 0xd9, 0xaa, 0x30, 0x9a, 0x97, 0x3f, 0x16, 0x2e, 0xba, 0x5b, 0xb8, 0xe8, 0xd7, 0xc2, 0x45,
	0xdf, 0x96, 0x6e, 0xe6, 0x6e, 0xe9, 0x66, 0x7e, 0x2e, 0xdd, 0xcc, 0x87, 0x37, 0x11, 0x4b, 0x3f,
	0x4d, 0xfb, 0xf5, 0x90, 0xc7, 0x8d, 0xed, 0xb8, 0x0d, 0x3d, 0xe0, 0xab, 0xf5, 0x4f, 0x73, 0xdb,
	0xd8, 0xff, 0x79, 0xd2, 0xf9, 0x84, 0x8a, 0x7e, 0x4e, 0xfd, 0x1e, 0xc7, 0xbf, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xa6, 0xa3, 0x57, 0xaf, 0x97, 0x04, 0x00, 0x00,
}

func (m *Game) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Game) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Game) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NextMark != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.NextMark))
		i--
		dAtA[i] = 0x68
	}
	if m.GuestMark != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.GuestMark))
		i--
		dAtA[i] = 0x60
	}
	if m.CreatorMark != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.CreatorMark))
		i--
		dAtA[i] = 0x58
	}
	if len(m.Guest) > 0 {
		i -= len(m.Guest)
		copy(dAtA[i:], m.Guest)
		i = encodeVarintGame(dAtA, i, uint64(len(m.Guest)))
		i--
		dAtA[i] = 0x52
	}
	if m.NumOfMoves != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.NumOfMoves))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Board) > 0 {
		dAtA2 := make([]byte, len(m.Board)*10)
		var j1 int
		for _, num := range m.Board {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintGame(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x42
	}
	if m.GameState != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.GameState))
		i--
		dAtA[i] = 0x38
	}
	if m.Reward != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.Reward))
		i--
		dAtA[i] = 0x30
	}
	if m.Strike != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.Strike))
		i--
		dAtA[i] = 0x28
	}
	if m.Cols != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.Cols))
		i--
		dAtA[i] = 0x20
	}
	if m.Rows != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.Rows))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintGame(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintGame(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateGame) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateGame) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateGame) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Reward != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.Reward))
		i--
		dAtA[i] = 0x28
	}
	if m.Strike != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.Strike))
		i--
		dAtA[i] = 0x20
	}
	if m.Cols != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.Cols))
		i--
		dAtA[i] = 0x18
	}
	if m.Rows != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.Rows))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintGame(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgJoinGame) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgJoinGame) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgJoinGame) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintGame(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Guest) > 0 {
		i -= len(m.Guest)
		copy(dAtA[i:], m.Guest)
		i = encodeVarintGame(dAtA, i, uint64(len(m.Guest)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCommitMove) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCommitMove) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCommitMove) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Col != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.Col))
		i--
		dAtA[i] = 0x18
	}
	if m.Row != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.Row))
		i--
		dAtA[i] = 0x10
	}
	if m.Player != 0 {
		i = encodeVarintGame(dAtA, i, uint64(m.Player))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGame(dAtA []byte, offset int, v uint64) int {
	offset -= sovGame(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Game) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovGame(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovGame(uint64(l))
	}
	if m.Rows != 0 {
		n += 1 + sovGame(uint64(m.Rows))
	}
	if m.Cols != 0 {
		n += 1 + sovGame(uint64(m.Cols))
	}
	if m.Strike != 0 {
		n += 1 + sovGame(uint64(m.Strike))
	}
	if m.Reward != 0 {
		n += 1 + sovGame(uint64(m.Reward))
	}
	if m.GameState != 0 {
		n += 1 + sovGame(uint64(m.GameState))
	}
	if len(m.Board) > 0 {
		l = 0
		for _, e := range m.Board {
			l += sovGame(uint64(e))
		}
		n += 1 + sovGame(uint64(l)) + l
	}
	if m.NumOfMoves != 0 {
		n += 1 + sovGame(uint64(m.NumOfMoves))
	}
	l = len(m.Guest)
	if l > 0 {
		n += 1 + l + sovGame(uint64(l))
	}
	if m.CreatorMark != 0 {
		n += 1 + sovGame(uint64(m.CreatorMark))
	}
	if m.GuestMark != 0 {
		n += 1 + sovGame(uint64(m.GuestMark))
	}
	if m.NextMark != 0 {
		n += 1 + sovGame(uint64(m.NextMark))
	}
	return n
}

func (m *MsgCreateGame) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovGame(uint64(l))
	}
	if m.Rows != 0 {
		n += 1 + sovGame(uint64(m.Rows))
	}
	if m.Cols != 0 {
		n += 1 + sovGame(uint64(m.Cols))
	}
	if m.Strike != 0 {
		n += 1 + sovGame(uint64(m.Strike))
	}
	if m.Reward != 0 {
		n += 1 + sovGame(uint64(m.Reward))
	}
	return n
}

func (m *MsgJoinGame) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Guest)
	if l > 0 {
		n += 1 + l + sovGame(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovGame(uint64(l))
	}
	return n
}

func (m *MsgCommitMove) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Player != 0 {
		n += 1 + sovGame(uint64(m.Player))
	}
	if m.Row != 0 {
		n += 1 + sovGame(uint64(m.Row))
	}
	if m.Col != 0 {
		n += 1 + sovGame(uint64(m.Col))
	}
	return n
}

func sovGame(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGame(x uint64) (n int) {
	return sovGame(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Game) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Game: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Game: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rows", wireType)
			}
			m.Rows = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Rows |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cols", wireType)
			}
			m.Cols = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cols |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Strike", wireType)
			}
			m.Strike = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Strike |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reward", wireType)
			}
			m.Reward = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reward |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GameState", wireType)
			}
			m.GameState = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GameState |= GameState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType == 0 {
				var v Mark
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGame
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= Mark(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Board = append(m.Board, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGame
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGame
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthGame
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				if elementCount != 0 && len(m.Board) == 0 {
					m.Board = make([]Mark, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v Mark
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGame
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= Mark(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Board = append(m.Board, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Board", wireType)
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumOfMoves", wireType)
			}
			m.NumOfMoves = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumOfMoves |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Guest", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Guest = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatorMark", wireType)
			}
			m.CreatorMark = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatorMark |= Mark(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuestMark", wireType)
			}
			m.GuestMark = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GuestMark |= Mark(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextMark", wireType)
			}
			m.NextMark = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextMark |= Mark(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGame(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGame
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateGame) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateGame: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateGame: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rows", wireType)
			}
			m.Rows = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Rows |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cols", wireType)
			}
			m.Cols = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cols |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Strike", wireType)
			}
			m.Strike = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Strike |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reward", wireType)
			}
			m.Reward = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reward |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGame(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGame
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgJoinGame) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgJoinGame: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgJoinGame: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Guest", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Guest = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGame
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGame
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGame(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGame
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCommitMove) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGame
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCommitMove: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCommitMove: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Player", wireType)
			}
			m.Player = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Player |= Mark(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Row", wireType)
			}
			m.Row = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Row |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Col", wireType)
			}
			m.Col = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGame
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Col |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGame(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGame
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGame(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGame
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGame
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGame
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGame
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGame
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGame
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGame        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGame          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGame = fmt.Errorf("proto: unexpected end of group")
)
